public enum TokenType {

	ID_PUBLIC_SCALAR, ID_PRIVATE_SCALAR, ID_PUBLIC_ARRAY, ID_PRIVATE_ARRAY, ID_PUBLIC_HASH, ID_PRIVATE_HASH, 
	STRING_LITERAL, INTEGER_LITERAL, CHARACTER_LITERAL, FLOATING_POINT_LITERAL, TYPE_STRING, TYPE_INTEGER, TYPE_CHARACTER, TYPE_FLOAT, TYPE_VOID, 
	SM_PLUS, SM_MINUS, SM_ASTERISK, SM_SLASH, SM_PERCENT, SM_ASSIGN, SM_LOGICAL_AND, SM_LOGICAL_OR, SM_LOGICAL_NOT, SM_LBRACE, SM_RBRACE, SM_LBRACKET, SM_RBRACKET, SM_LPAREN, SM_RPAREN;
	
}
